spring:
  application:
    name: zuulserver
server:
   port: 7777
   servlet:
     context-path: /cloud
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
zuul:
  routes:
    eurekaclient: /eclient/**
    feignclient: /fclient/**
    securedclient: /sclient/**
  sensetiveHeaders: Cookie, Set-Cookie
ribbon:
  ReadTimeout: 60000